### ISSUE TITLE
[enhancement] ship with a default sets of facts

### ISSUE THREAD

**Issue by GeoffWilliams** [dylanratcliffe/controlrepo_gem#2]
## Overview
It would be a great enhancement if we could ship a bunch of default facts for all target platforms inside the gem, along with a method for users to override/augment them.

## Why needed
Increase programmer productivity and time/effort cost to deploy testing

## How to do it?
Create a resources directory that ships as part of the gem -- see http://stackoverflow.com/questions/6128540/packaging-a-read-only-data-file-with-a-ruby-gem and use this to read the default files

**Comment by dylanratcliffe** [comment]
Fixed
