### ISSUE TITLE
[enhancement] quickstart guide for the lazy/impatient (me)

### ISSUE THREAD

**Issue by GeoffWilliams** [dylanratcliffe/controlrepo_gem#3]
## Overview
 Would like a boom style quickstart guide that gets users up and running in as few steps and words as possible.  Lets use this ticket to build the steps and then paste it into a new file or the readme.

So far we have:
1.  Add `gem 'controlrepo'` to Gemfile
2.  Add `require 'controlrepo/rake_tasks'` to Rakefile

Next step seems to be making config files

**Comment by dylanratcliffe** [comment]
Fixed
